// Source data generated by scripts/search-engine (Gemini + Google Search
// research on "ambrose patterson"), reviewed by hand before landing here.

export const AROUND_THE_WEB_INTRO =
  "Ambrose Patterson's life runs from Melbourne to Paris to Hawaii to Seattle, and the record of it is scattered accordingly — a museum collection page here, a university archive there, a gallery listing somewhere else. This is a starting map of where to see more of his work, read further, and explore the people and circles that shaped him.";

export interface Resource {
  title: string;
  url: string;
  summary: string;
  hasImages: boolean;
  imageNote?: string;
}

export interface ResourceCategory {
  key: string;
  label: string;
  kicker: string;
  entries: Resource[];
}

export const resourceCategories: ResourceCategory[] = [
  {
    key: "biography_background",
    label: "Biography & Background",
    kicker: "Start here for the arc of his life.",
    entries: [
      {
        title: "Ambrose McCarthy Patterson — Wikipedia",
        url: "https://en.wikipedia.org/wiki/Ambrose_McCarthy_Patterson",
        summary:
          "A comprehensive biographical overview covering his early years in Australia, his time in Paris exhibiting at the Salon d'Automne, and his later career in Hawaii and Seattle.",
        hasImages: false,
      },
      {
        title: "Ambrose Patterson — UW Paul G. Allen School",
        url: "https://www.cs.washington.edu/who-we-are/art-allen-school/uw-artists/ambrose-patterson/",
        summary:
          "A University of Washington page on Patterson's role establishing the UW School of Painting and Design, tracing his journey from Paris to Seattle and his impact on Northwest arts.",
        hasImages: true,
        imageNote: "Includes his paintings 'Waves' and 'Studio'.",
      },
    ],
  },
  {
    key: "galleries_museums",
    label: "Galleries & Museums",
    kicker:
      "Where his paintings live today, in public and commercial collections.",
    entries: [
      {
        title: "Woodside / Braseth Gallery",
        url: "https://woodsidebrasethgallery.com/artists/ambrose-patterson/",
        summary:
          "This Seattle gallery represents Patterson's estate, positioning him as a major figure in Pacific Northwest modernism, with a gallery of available paintings.",
        hasImages: true,
        imageNote: "Thumbnails of available artworks.",
      },
      {
        title: "Art Gallery of South Australia (AGSA)",
        url: "https://www.agsa.sa.gov.au/collection-publications/collection/creators/ambrose-patterson/6240/",
        summary:
          "The creator profile for Patterson at AGSA, listing works in the permanent collection including his 1904 painting 'Le bar, Saint-Jacques, Paris'.",
        hasImages: true,
        imageNote: "Images of works held in the museum's collection.",
      },
    ],
  },
  {
    key: "image_sources",
    label: "Image Sources",
    kicker: "The deepest visual archives of his actual work.",
    entries: [
      {
        title: "MutualArt — 37 Artworks at Auction",
        url: "https://www.mutualart.com/Artist/Ambrose-Patterson/291CEAAF84D08185",
        summary:
          "A database of Patterson's work that has appeared at auction — a visual archive of paintings, woodcuts, and prints, with realized prices and market data.",
        hasImages: true,
        imageNote: "High-resolution images of dozens of paintings and prints.",
      },
    ],
  },
  {
    key: "influences_related",
    label: "Influences & Related",
    kicker: "The Paris circle and the people around him.",
    entries: [
      {
        title: "Portrait of Ambrose Patterson — National Portrait Gallery",
        url: "https://www.portrait.gov.au/portraits/2003.44/portrait-of-ambrose-patterson",
        summary:
          "A 1901–1902 portrait of Patterson painted by his friend and fellow Australian artist Hugh Ramsay, with the story of their Paris friendship and how Patterson later cropped the damaged canvas himself.",
        hasImages: true,
        imageNote: "Image of the cropped Hugh Ramsay portrait.",
      },
      {
        title: "Self-portrait with Patterson, Lambert, Ramsay and Adams — NGA",
        url: "https://digital.nga.gov.au/archive/exhibition/lambert/detail.cfm%3Firn=163176.html",
        summary:
          "A group portrait by George W. Lambert featuring Patterson alongside other expatriate Australian artists in Paris, with context on their shared bohemian circle.",
        hasImages: true,
        imageNote: "Image of the group portrait.",
      },
    ],
  },
  {
    key: "further_reading",
    label: "Further Reading",
    kicker: "For going deeper than a web page can take you.",
    entries: [
      {
        title: "Ambrose Patterson: His Life & Art",
        url: "https://ambrosepatterson.com.au/",
        summary:
          "The first authoritative monograph on Patterson, by Jane Alexander — tracing his life from bohemian Paris to the Pacific Northwest, drawn from extensive family and institutional archives.",
        hasImages: true,
        imageNote: "Book cover and selected illustrations from the monograph.",
      },
      {
        title: "Ambrose Patterson papers, 1902–1982 — Archives West",
        url: "https://archiveswest.orbiscascade.org/ark:80444/xv95822",
        summary:
          "A finding aid for the Patterson papers at the University of Washington Libraries — correspondence, exhibition catalogs, and writings relating to Ambrose and his wife Viola.",
        hasImages: false,
      },
    ],
  },
];
