// Source data generated by scripts/ai-video-analysis (Gemini review of
// "Danielle Knapp - Ambrose Patterson.mp4"), reviewed by hand before landing here.

// TODO: set once the interview is uploaded and you've picked which account to post it from.
// Leaving this empty hides the video embed and VideoObject schema — chapters/highlights
// still display as plain text.
export const YOUTUBE_VIDEO_ID = "";
export const hasVideo = YOUTUBE_VIDEO_ID.length > 0;

export const INTERVIEW_TITLE =
  "Danielle Knapp on Ambrose Patterson's Seattle Legacy";

export const INTERVIEW_SUMMARY =
  "Danielle Knapp, Curator of American and Regional Art at the Jordan Schnitzer Museum of Art, discusses her long-standing research into artist Ambrose Patterson, highlighting the lack of comprehensive written material on his significant contributions to modern art in Seattle and expressing her excitement for a new monograph on his work.";

export const INTERVIEW_SPEAKERS = ["Danielle Knapp"];

export interface Chapter {
  start: string;
  end: string;
  title: string;
  summary: string;
}

export const chapters: Chapter[] = [
  {
    start: "00:00",
    end: "00:33",
    title: "Introduction and Connection to Ambrose Patterson",
    summary:
      "Danielle Knapp introduces herself as a curator at the Jordan Schnitzer Museum of Art in Eugene, Oregon, located south of Seattle where Ambrose Patterson spent five decades of his life. She expresses her privilege to share thoughts on a new monograph about Patterson.",
  },
  {
    start: "00:33",
    end: "01:27",
    title: "Discovering Patterson's Work as an Intern",
    summary:
      "Knapp recounts her first encounter with Ambrose Patterson's work nearly 20 years ago as a graduate student and intern at the museum, where she was tasked with researching him for potential acquisitions, despite not having heard his name before.",
  },
  {
    start: "01:27",
    end: "02:49",
    title: "The Lack of Written Work and Her Thesis",
    summary:
      "She realized there was very little written about Patterson's work, especially regarding its interpretation, reception, and impact on the artistic history of the region. This led her to make Patterson the subject of her master's thesis, 'Rethinking Ambrose Patterson and Modern Art in Seattle'.",
  },
  {
    start: "02:49",
    end: "03:14",
    title: "Patterson's Presence in the Museum Collection",
    summary:
      "Knapp shares that her museum now holds 17 examples of Patterson's drawings and prints, and she expresses a wish for some of his larger paintings. Her interest in his work has remained strong over the years.",
  },
  {
    start: "03:14",
    end: "04:38",
    title: "Patterson's Influence on Seattle's Art Scene",
    summary:
      "She reflects on Patterson's significance as an artist of his caliber and worldliness arriving in Seattle at a pivotal moment for artistic and intellectual growth. His early involvement in developing the School of Painting and Design at the University of Washington was crucial.",
  },
  {
    start: "04:38",
    end: "05:27",
    title: "Community Engagement and Artistic Movements",
    summary:
      "Knapp highlights Patterson's role in establishing major art museums in Seattle, his engagement in salon-style conversations about art, and his travels to Mexico to study fresco painting. He also worked with printmaker societies to create exhibition opportunities.",
  },
  {
    start: "05:27",
    end: "06:35",
    title: "Patterson's Artistic Exploration and Personal Impact",
    summary:
      "She discusses Patterson's ability to balance his artistic impulses with decades of teaching, training students who became nationally and internationally known. His exploration of modernism, naturalism, and impressionism deeply influenced her own art historical development.",
  },
  {
    start: "06:35",
    end: "07:18",
    title: "Celebrating the New Monograph",
    summary:
      "Knapp expresses her absolute thrill that the new book on Patterson is being released. She is honored to have contributed to the research and looks forward to celebrating his work with others, wishing everyone well.",
  },
];

export type HighlightType =
  | "strong_opening"
  | "key_insight"
  | "emotional_moment"
  | "strong_closing";

export interface Highlight {
  start: string;
  end: string;
  type: HighlightType;
  speaker: string;
  displayQuote: string;
}

const HIGHLIGHT_LABELS: Record<HighlightType, string> = {
  strong_opening: "Opening",
  key_insight: "Key insight",
  emotional_moment: "Personal moment",
  strong_closing: "Closing",
};

export function highlightLabel(type: HighlightType): string {
  return HIGHLIGHT_LABELS[type];
}

export const highlights: Highlight[] = [
  {
    start: "00:24",
    end: "00:33",
    type: "strong_opening",
    speaker: "Danielle Knapp",
    displayQuote:
      "It is such a privilege to share a few thoughts with you today in celebration on the occasion of this very important monograph about Patterson.",
  },
  {
    start: "01:27",
    end: "01:57",
    type: "key_insight",
    speaker: "Danielle Knapp",
    displayQuote:
      "Very early on, I realized, in my excitement to have this important project, that there was very little written about his work. Certainly not enough written that made clear how important he had been to the community in Seattle, his significance to the University of Washington. Very little in terms of long-form writing about how we interpret his work, how his work was received at the time, and what the impact has been in the artistic history of this region.",
  },
  {
    start: "02:30",
    end: "02:48",
    type: "emotional_moment",
    speaker: "Danielle Knapp",
    displayQuote:
      "To be introduced to this artist's work, it just really felt like there was something there that I was compelled to learn more about. So I took that charge, 'find out everything you can about Ambrose Patterson,' and that eventually became my thesis, 'Rethinking Ambrose Patterson and Modern Art in Seattle.'",
  },
  {
    start: "03:25",
    end: "03:48",
    type: "key_insight",
    speaker: "Danielle Knapp",
    displayQuote:
      "Think about what that meant to be an artist of his caliber, his training, his worldliness, to arrive in Seattle at a moment where the city was really about to experience a boom in artistic inquiry and intellectual curiosity, and a deciding moment for the city of Seattle about what kind of artistic place and education it wanted to be and provide.",
  },
  {
    start: "06:35",
    end: "07:18",
    type: "strong_closing",
    speaker: "Danielle Knapp",
    displayQuote:
      "I am just absolutely thrilled that this book is now coming out. Not only will it document his contributions and his career, but also be a way of introducing his work to so many other people. I'm so honored to have been any small part of the research that led to this moment, that we can all celebrate together, Jane Alexander's work, everyone who worked on this book, and share in our appreciation for such an important artist, truly admired around the world. I wish I could be there with you all to give my congratulations in person. I hope to see the book very soon, and I wish you all well. Thank you so much for your time.",
  },
];
