// Source data generated by scripts/search-engine (Gemini + Google Search
// research on each artist), reviewed by hand before landing here. See
// scripts/search-engine/output/<slug>.json for the raw research pass.

export interface Resource {
  title: string;
  url: string;
  summary: string;
  hasImages: boolean;
  imageNote?: string;
}

export interface ResourceCategory {
  key: string;
  label: string;
  entries: Resource[];
}

export interface HistoricalNote {
  heading: string;
  paragraphs: string[];
  sources: { label: string; url: string }[];
}

export interface RelatedArtist {
  slug: string;
  name: string;
  dates: string;
  /** Why this artist has a page on an Ambrose Patterson site — shown as an intro callout. */
  connectionToPatterson: string;
  overview: string;
  categories: ResourceCategory[];
  /** Optional link to a dedicated on-site video page about this artist. */
  video?: { href: string; label: string };
  /** Optional sourced context on a specific biographical detail, shown in a neutral (non-primary) card. */
  historicalNote?: HistoricalNote;
}

export const relatedArtists: RelatedArtist[] = [
  {
    slug: "hugh-ramsay",
    name: "Hugh Ramsay",
    dates: "1877–1906",
    connectionToPatterson:
      "Ramsay and Patterson trained together under Bernard Hall at the National Gallery School in Melbourne before both left for Paris around the turn of the century. In 1901–02 Ramsay painted a full-length portrait of Patterson; the canvas was later damaged, and Patterson himself cropped it down to the fragment held today by the National Portrait Gallery. Ramsay died of tuberculosis in 1906, aged 28, cutting short one of the most promising careers of his generation.",
    overview:
      "Hugh Ramsay (1877–1906) was a highly gifted Australian artist whose promising career was cut short by tuberculosis at age 28. He is celebrated for tonally subtle portraiture — influenced by Velázquez, Whistler, and Sargent — and achieved early success when four paintings were accepted into the 1902 New Salon in Paris. His work is held in major Australian institutions today.",
    video: {
      href: "/press/around-the-web/hugh-ramsay/video",
      label:
        "Watch: NGA curator Dr. Deborah Hart on Hugh Ramsay's short, brilliant life",
    },
    historicalNote: {
      heading: "A note on his engagement",
      paragraphs: [
        "Around 1899, while still in Melbourne, Ramsay entered an unofficial engagement with Lischen Muller, a German student he had met that year. Born around 1885, she was about 14–15 when they became engaged, shortly before he sailed for Europe in September 1900. She sat for several of his works, including Consolation (1899–1901) and the 1904 portrait Lady with a Fan. Ramsay ended the roughly five-year engagement in August 1904 as his tuberculosis worsened — the National Portrait Gallery suggests he may have done so “perhaps to spare her further grief, or on medical advice.”",
        "By the standards of the time this wasn't a legal transgression. Betrothal carried no minimum age — it was a social promise, not a registered legal act — and even marriage at that age would have been lawful: colonial Victoria inherited English common law's historic minimum marriageable age of 12 for girls and 14 for boys, a floor that stayed in practice until the Commonwealth's Marriage Act 1961 introduced real statutory minimums, later equalised to 18 for both sexes in 1991. Victoria's age of consent for sexual activity, by contrast, had already been raised to 16 around 1891 — though nothing in the historical record indicates the relationship was sexual.",
      ],
      sources: [
        {
          label: "Wunderkind Lost — National Portrait Gallery",
          url: "https://www.portrait.gov.au/magazines/65/wunderkind-lost",
        },
        {
          label: "Hugh Ramsay — Design and Art Australia Online",
          url: "https://www.daao.org.au/bio/hugh-ramsay/biography/",
        },
        {
          label: "Marriage in Australia — Wikipedia",
          url: "https://en.wikipedia.org/wiki/Marriage_in_Australia",
        },
      ],
    },
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "Hugh Ramsay — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/ramsay-hugh-8150",
            summary:
              "A comprehensive biographical entry covering Ramsay's education at the National Gallery schools and his rapid rise to international acclaim before his early death.",
            hasImages: false,
          },
          {
            title: "Hugh Ramsay — National Portrait Gallery",
            url: "https://www.portrait.gov.au/people/hugh-ramsay-1877",
            summary:
              "An overview of Ramsay's life and career, his time in Paris, his critical success at the New Salon, and his patronage by Dame Nellie Melba.",
            hasImages: true,
            imageNote: "His 1901–1902 full-length self-portrait.",
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "Hugh Ramsay — Artists | NGV",
            url: "https://www.ngv.vic.gov.au/explore/collection/artist/488/",
            summary:
              "The National Gallery of Victoria's collection page for Ramsay, listing 21 of his works held by the institution.",
            hasImages: true,
            imageNote:
              "21 artworks in the NGV collection, including self-portraits and studies.",
          },
          {
            title:
              "Hugh Ramsay Exhibition Tour — National Gallery of Australia",
            url: "https://nga.gov.au/on-demand/hugh-ramsay-exhibition-tour/",
            summary:
              "The NGA's major retrospective of Ramsay, the first in over 25 years, curating paintings, drawings, sketchbooks, and letters from collections nationwide.",
            hasImages: false,
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "Hugh Ramsay Works — National Gallery of Australia",
            url: "https://nga.gov.au/ramsay/works.cfm",
            summary:
              "A gallery page showcasing the artworks displayed in the NGA's comprehensive Hugh Ramsay retrospective.",
            hasImages: true,
            imageNote:
              "High-resolution images of works from the NGA retrospective.",
          },
          {
            title:
              "The art and archive of Hugh Ramsay — National Gallery of Australia",
            url: "https://nga.gov.au/stories-ideas/the-art-and-archive-of-hugh-ramsay/",
            summary:
              "An archival look at Ramsay's painting tools, photographs, letters, and sketchbooks.",
            hasImages: true,
            imageNote:
              "His wooden paintbox, watercolour tins, brushes, and a self-portrait smoking in front of a piano.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "Portrait of Ambrose Patterson — National Portrait Gallery",
            url: "https://www.portrait.gov.au/portraits/2003.44/portrait-of-ambrose-patterson",
            summary:
              "Ramsay's 1901–1902 portrait of his friend and fellow Australian expatriate Ambrose Patterson, painted in Paris — later damaged and cropped by Patterson himself.",
            hasImages: true,
            imageNote: "Image of the cropped portrait of Ambrose Patterson.",
          },
          {
            title: "Hugh Ramsay Symposium — Ramsay + Lambert",
            url: "https://nga.gov.au/on-demand/hugh-ramsay-symposium-gray-nga-ramsay-lambert/",
            summary:
              "A lecture on the close relationship and mutual influence between Ramsay and fellow Australian artist George Lambert during their time in Paris, studying Velázquez and Sargent together.",
            hasImages: false,
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title: "Hugh Ramsay: His Life and Work — Patricia Fullerton",
            url: "https://www.treloars.com/pages/books/143053/hugh-ramsay-patricia-fullerton/hugh-ramsay-his-life-and-work",
            summary:
              "The definitive 1988 monograph, based largely on Ramsay's own letters — a crucial text for researchers.",
            hasImages: false,
          },
          {
            title:
              "Hugh Ramsay: a consideration of his life and work — Minerva Access",
            url: "https://minerva-access.unimelb.edu.au/handle/11343/37215",
            summary:
              "A University of Melbourne thesis offering a scholarly consideration of Ramsay's life, family background, and artistic output.",
            hasImages: false,
          },
        ],
      },
      {
        key: "news_press",
        label: "News & Press",
        entries: [
          {
            title:
              "Hugh Ramsay review: a virtuoso of white on white who left the art world too soon",
            url: "https://theconversation.com/hugh-ramsay-review-a-virtuoso-of-white-on-white-who-left-the-art-world-too-soon-126587",
            summary:
              "A 2019 review of the NGA's retrospective, praising Ramsay's virtuosic technique and lamenting the early loss of his talent.",
            hasImages: false,
          },
          {
            title: "Hugh Ramsay: Bright Star — National Gallery of Australia",
            url: "https://nga.gov.au/stories-ideas/hugh-ramsay-bright-star/",
            summary:
              "A feature by the NGA's Head Curator of Australian Art drawing parallels between Ramsay and the poet John Keats, both dead of tuberculosis at a young age.",
            hasImages: true,
            imageNote:
              "Ramsay's self-portraits and key paintings discussed in the article.",
          },
        ],
      },
    ],
  },
  {
    slug: "george-w-lambert",
    name: "George W. Lambert",
    dates: "1873–1930",
    connectionToPatterson:
      "Lambert painted a group self-portrait, held by the National Gallery of Australia, that included Patterson alongside Hugh Ramsay, Amy Lambert, and the writer Arthur Adams — a document of the same Paris bohemian circle Patterson moved in as a young expatriate. Like Patterson, Lambert trained in Melbourne before continuing his studies abroad, and the two crossed paths through the same close-knit group of Australian artists in Paris around the turn of the century.",
    overview:
      "George Washington Lambert (1873–1930) was a prominent Australian artist known for his portraiture, 'puzzle pictures', and his work as an official war artist during World War I. He trained in Melbourne before moving through Paris and London, and became one of the most influential Australian artists of his generation.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "George Washington Lambert — Wikipedia",
            url: "https://en.wikipedia.org/wiki/George_Washington_Lambert",
            summary:
              "A comprehensive biographical overview covering Lambert's early years, his career as an official war artist, and his later sculptural work, with details on his influences and major exhibitions.",
            hasImages: true,
            imageNote: "Paintings and a photograph of the artist.",
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "Important People (Lambert) — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Important_People_(Lambert)",
            summary:
              "Details Lambert's 1914–1921 painting 'Important People', held at the Art Gallery of New South Wales, its allegorical meaning and critical reception.",
            hasImages: true,
            imageNote: "High-resolution image of 'Important People'.",
          },
          {
            title: "A Sergeant of the Light Horse — Wikipedia",
            url: "https://en.wikipedia.org/wiki/A_Sergeant_of_the_Light_Horse",
            summary:
              "Lambert's 1920 portrait of an Australian soldier in Palestine, held by the NGV, and his approach to composite military portraiture.",
            hasImages: true,
            imageNote: "High-resolution image of the painting.",
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title:
              "Category: Paintings by George Washington Lambert — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Category:Paintings_by_George_Washington_Lambert",
            summary:
              "A hub listing articles on individual paintings by Lambert, with images and analysis across various periods of his career.",
            hasImages: false,
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title:
              "Self-portrait with Ambrose Patterson, Amy Lambert, Hugh Ramsay and Arthur Adams — National Gallery of Australia",
            url: "https://digital.nga.gov.au/archive/exhibition/lambert/detail.cfm%3Firn=163176.html",
            summary:
              "A group portrait by Lambert featuring Ambrose Patterson alongside other expatriate Australian artists in Paris, with context on their shared bohemian circle.",
            hasImages: true,
            imageNote: "Image of the group portrait featuring Patterson.",
          },
          {
            title: "The White Glove — Wikipedia",
            url: "https://en.wikipedia.org/wiki/The_White_Glove",
            summary:
              "Lambert's 1921 portrait of Miss Gladys Neville Collins, highlighting the influence of Joshua Reynolds and John Singer Sargent on his style.",
            hasImages: true,
            imageNote: "Image of the painting.",
          },
          {
            title: "Self-Portrait with Gladioli — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Self-Portrait_with_Gladioli",
            summary:
              "Analysis of Lambert's 1922 self-portrait and its resemblance to Reynolds' self-portraits and classical sculpture.",
            hasImages: true,
            imageNote: "Image of the painting.",
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title: "Chesham Street — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Chesham_Street",
            summary:
              "Lambert's 1910 'puzzle picture' depicting a medical examination, with context on his Edwardian period and use of narrative ambiguity.",
            hasImages: true,
            imageNote: "Image of the painting.",
          },
          {
            title: "Anzacs Bathing — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Anzacs_Bathing",
            summary:
              "Lambert's 1916 painting of soldiers at Gallipoli, and his references to Michelangelo and Greek mythology as an official war artist.",
            hasImages: true,
            imageNote: "Image of the painting.",
          },
        ],
      },
    ],
  },
  {
    slug: "rupert-bunny",
    name: "Rupert Bunny",
    dates: "1864–1947",
    connectionToPatterson:
      "Bunny was part of the wider generation of Australian expatriate painters — Patterson among them — who left Melbourne for Paris around the turn of the century and built careers exhibiting in the French Salon system. The two moved in overlapping circles of Australian artists living and showing work in Paris during the Belle Époque, before Patterson's own path continued on to Hawaii and Seattle.",
    overview:
      "Rupert Bunny (1864–1947) was one of the most successful Australian expatriate artists of his generation, spending nearly 50 years in France. He is celebrated for sumptuous Belle Époque paintings of Parisian leisure, mythological scenes, and later landscapes, achieving significant recognition in the French Salon system.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "Rupert Charles Bunny — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/bunny-rupert-charles-5422/text9195",
            summary:
              "A comprehensive biographical entry on Bunny's early life in Melbourne, his career in Paris, and his return to Australia.",
            hasImages: false,
          },
          {
            title: "Rupert Bunny — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Rupert_Bunny",
            summary:
              "An overview of Bunny's life, education, and success at the Paris Salon, covering his transition from neoclassical and symbolist work to later landscapes.",
            hasImages: true,
            imageNote:
              "A self-portrait and several of his most famous paintings.",
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "Rupert BUNNY — Collection Online | NGV",
            url: "https://www.ngv.vic.gov.au/explore/collection/artist/1149/",
            summary:
              "The NGV's substantial Bunny collection, including his 'Madame Melba' portrait and numerous sketches.",
            hasImages: true,
            imageNote:
              "Over 80 artworks including major paintings and preparatory sketches.",
          },
          {
            title: "Rupert Bunny — National Gallery of Australia",
            url: "https://nga.gov.au/exhibitions/rupert-bunny/",
            summary:
              "The NGA's collection of more than 100 works by Bunny, from early botanical garden landscapes to late mythological paintings.",
            hasImages: true,
            imageNote: "Images of key works like 'Qui vient? [Who comes?]'.",
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "Rupert Bunny — 59 artworks — WikiArt.org",
            url: "https://www.wikiart.org/en/rupert-bunny",
            summary:
              "A visual database of Bunny's paintings organized chronologically and by style, spanning his Belle Époque and mythological works.",
            hasImages: true,
            imageNote: "Dozens of images filterable by date and genre.",
          },
          {
            title: "Rupert Bunny Artworks at Auction — MutualArt",
            url: "https://www.mutualart.com/Artist/Rupert-Bunny",
            summary:
              "An archive of over 400 artworks by Bunny that have appeared at auction, spanning landscapes, portraits, and sketches in private collections.",
            hasImages: true,
            imageNote: "Hundreds of images from auction records.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "Rupert Bunny's Mythologies — National Gallery of Australia",
            url: "https://nga.gov.au/exhibitions/rupert-bunnys-mythologies/",
            summary:
              "An essay on Bunny's fascination with classical and Christian mythology, and how he assimilated Symbolism and Puvis de Chavannes into his own allegorical style.",
            hasImages: false,
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title:
              "The life and art of Rupert Bunny: a catalogue raisonné in two volumes",
            url: "https://catalogue.nla.gov.au/catalog/7289251",
            summary:
              "David Thomas's definitive 2017 two-volume catalogue raisonné, covering Bunny's oils, monotypes, sketchbooks, and exhibition history.",
            hasImages: false,
          },
          {
            title: "Rupert Bunny, 1864–1947 — David Thomas",
            url: "https://catalogue.nla.gov.au/catalog/642369",
            summary:
              "The original 1970 monograph on Bunny, a foundational text for studying his life and early critical reception.",
            hasImages: false,
          },
        ],
      },
      {
        key: "news_press",
        label: "News & Press",
        entries: [
          {
            title:
              "The Cosmopolitans: In Gallery Two — National Portrait Gallery",
            url: "https://www.portrait.gov.au/exhibitions/the-cosmopolitans-2023",
            summary:
              "A 2023–2024 exhibition featuring Bunny alongside his contemporaries, highlighting the generation of Australian artists who traveled to London and Paris around 1900.",
            hasImages: true,
            imageNote:
              "Installation views and selected portraits from the exhibition.",
          },
          {
            title:
              "Rupert Bunny Foundation Visual Arts Fellowship — City of Port Phillip",
            url: "https://www.portphillip.vic.gov.au/people-and-community/funds-grants-and-subsidies/rupert-bunny-foundation-visual-arts-fellowship",
            summary:
              "A contemporary visual arts fellowship established in 2005 using funds from the insurance of a destroyed Rupert Bunny painting.",
            hasImages: false,
          },
        ],
      },
    ],
  },
  {
    slug: "e-phillips-fox",
    name: "E. Phillips Fox",
    dates: "1865–1915",
    connectionToPatterson:
      "Like Patterson, Fox trained in Melbourne before continuing his studies in Paris, and both were part of the wave of Australian expatriate painters who carried French Impressionist and Post-Impressionist technique back into Australian art. Fox's role co-founding the Melbourne School of Art parallels Patterson's own later move into art education, when he went on to establish the University of Washington's School of Painting and Design.",
    overview:
      "Emanuel Phillips Fox (1865–1915) was a prominent Australian Impressionist and Post-Impressionist painter celebrated for his vibrant use of light and color. After training in Melbourne and Paris, he became a key figure in the Heidelberg School and co-founded the Melbourne School of Art, often in creative partnership with his wife, the artist Ethel Carrick Fox.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "Emanuel Phillips Fox — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/fox-emanuel-phillips-6228",
            summary:
              "An authoritative academic biography detailing Fox's training under Gérôme in Paris and his establishment of the Melbourne School of Art.",
            hasImages: false,
          },
          {
            title: "E. Phillips Fox — Wikipedia",
            url: "https://en.wikipedia.org/wiki/E._Phillips_Fox",
            summary:
              "A comprehensive overview of Fox's early life in Melbourne, his studies in Europe, his role in the second phase of the Heidelberg School, and his marriage to Ethel Carrick.",
            hasImages: false,
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "E. Phillips Fox — National Portrait Gallery",
            url: "https://www.portrait.gov.au/people/emanuel-phillips-fox-1865",
            summary:
              "The National Portrait Gallery's collection page for Fox, with a biographical summary of his time in France and England and his portraiture work.",
            hasImages: true,
            imageNote:
              "Portraits by Fox held in the National Portrait Gallery collection.",
          },
          {
            title:
              "Between the Bush and Boudoir — National Gallery of Australia",
            url: "https://nga.gov.au/exhibitions/between-the-bush-and-boudoir/",
            summary:
              "An overview of Fox's place among a new generation of Australian impressionists in the 1880s, blending European plein-air traditions with Australian subjects.",
            hasImages: false,
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "Emanuel Phillips Fox — 82 artworks — Art Renewal Center",
            url: "https://www.artrenewal.org/artists/emanuel-phillips-fox/2181",
            summary:
              "A digital gallery of Fox's paintings, drawings, and oils, showcasing his mastery of light and color.",
            hasImages: true,
            imageNote:
              "High-resolution images of 82 artworks spanning his career.",
          },
          {
            title:
              "Emanuel Phillips Fox: A collection of 76 paintings (HD) — YouTube",
            url: "https://www.youtube.com/watch?v=TKlUlRkb6Us",
            summary:
              "A video compilation of 76 of Fox's paintings in high definition, with a biographical description covering his landscapes, portraits, and Edwardian scenes.",
            hasImages: true,
            imageNote: "Video slideshow of 76 high-definition images.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "The poetry of the world — National Gallery of Australia",
            url: "https://nga.gov.au/stories-ideas/the-poetry-of-the-world/",
            summary:
              "An essay on Ethel Carrick, Fox's wife and a significant Post-Impressionist painter in her own right, contextualizing their mutual support and shared travels.",
            hasImages: true,
            imageNote: "Ethel Carrick's paintings and archival material.",
          },
          {
            title:
              "Ethel Carrick Fox and Emanuel Phillips Fox: A Historic Partnership — Leonard Joel Auctions",
            url: "https://www.leonardjoel.com.au/newsletter/the-estate-of-graham-joel/",
            summary:
              "An article on the artistic partnership between Fox and Ethel Carrick Fox, and their shared life of en plein air painting across Europe and North Africa after their 1905 marriage.",
            hasImages: false,
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title: "E. Phillips Fox: His Life and Art — Ruth Zubans",
            url: "https://books.google.com.au/books/about/E_Phillips_Fox.html?id=VbILAQAAMAAJ&redir_esc=y",
            summary:
              "A comprehensive 1995 monograph by art historian Ruth Zubans, considered the definitive text on Fox's life, Paris years, and development of Impressionist subject painting.",
            hasImages: false,
          },
        ],
      },
      {
        key: "news_press",
        label: "News & Press",
        entries: [
          {
            title: "Ethel Carrick — National Gallery of Australia",
            url: "https://nga.gov.au/exhibitions/ethel-carrick/",
            summary:
              "A major retrospective of Ethel Carrick (Dec 2024 – Apr 2025) re-evaluating her career and output during and after her marriage to Fox.",
            hasImages: true,
            imageNote:
              "Promotional images and selected artworks from the exhibition.",
          },
          {
            title: "CAM celebrates painting prize — Midland Express",
            url: "https://midlandexpress.com.au/latest-news/2024/10/01/len-fox-painting-award-celebrated-at-castlemaine-art-museum/",
            summary:
              "Coverage of the 2024 Len Fox Painting Award at the Castlemaine Art Museum, a biennial prize commemorating Fox's life and work.",
            hasImages: false,
          },
        ],
      },
    ],
  },
  {
    slug: "iso-rae",
    name: "Iso Rae",
    dates: "1860–1940",
    connectionToPatterson:
      "Like Patterson, Rae trained at the National Gallery School in Melbourne before continuing her artistic development in France, joining the Étaples art colony in 1890 — part of the same wave of Australian expatriate painters who left Melbourne for France around the turn of the century and built careers exhibiting and painting abroad.",
    overview:
      "Isobel (Iso) Rae (1860–1940) was an Australian Impressionist and Post-Impressionist painter who spent most of her career in France as part of the Étaples art colony. She is particularly notable for being one of only two Australian women artists to document the First World War firsthand, producing hundreds of pastel drawings of the Étaples Army Base Camp. Her work is held in major institutions including the National Gallery of Victoria and the Australian War Memorial.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "Iso Rae — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Iso_Rae",
            summary:
              "A comprehensive biographical overview of Rae's early life in Melbourne, her move to France, her involvement in the Étaples art colony, and her unofficial war art during World War I.",
            hasImages: true,
            imageNote: "Her painting 'Young Girl, Étaples' and archival material.",
          },
          {
            title: "Iso Rae, the Unrecognised War Artist — Kathryn's history blog",
            url: "http://www.kathrynshistoryblog.com/2021/03/iso-rae-unrecognised-war-artist.html",
            summary:
              "A historical blog post on Rae's time in Étaples during WWI, her decision to stay in France, and her 200 drawings documenting life in the military camps.",
            hasImages: true,
            imageNote: "A photograph of Iso Rae seated in a group.",
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "Iso Rae — Young girl, Étaples (c. 1892) — NGV",
            url: "https://www.ngv.vic.gov.au/explore/collection/work/144974/",
            summary:
              "The NGV's collection page for Rae's large-scale oil painting 'Young girl, Étaples', with artwork details, provenance, and context about her time in the French fishing village.",
            hasImages: true,
            imageNote: "High-resolution image of the painting.",
          },
          {
            title: "Iso Rae — Australian War Memorial",
            url: "https://www.awm.gov.au/collection/P10676602",
            summary:
              "The Australian War Memorial's overview of Rae's contributions as an unofficial war artist, and its collection of her pastel drawings of the Étaples army camp.",
            hasImages: true,
            imageNote: "Several pastel drawings from the WWI Étaples army camp.",
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "Category: Étaples art colony — Wikimedia Commons",
            url: "https://commons.wikimedia.org/wiki/Category:%C3%89taples_art_colony",
            summary:
              "A Wikimedia Commons category of public-domain images from the Étaples art colony, including several works by Iso Rae such as 'Cinema Queue' and 'Les Rogations'.",
            hasImages: true,
            imageNote: "High-res images of paintings by artists in the Étaples colony.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "Colonie artistique d'Étaples — Wikipédia",
            url: "https://fr.wikipedia.org/wiki/Colonie_artistique_d%27%C3%89taples",
            summary:
              "The French Wikipedia page for the Étaples art colony, the international group of artists Rae joined in 1890, with context on the movement and its members.",
            hasImages: true,
            imageNote: "Paintings by artists of the colony.",
          },
          {
            title: "Behind the lines — NGV",
            url: "https://www.ngv.vic.gov.au/essay/behind-the-lines/",
            summary:
              "An NGV essay on the role of women artists during WWI, contextualizing Rae's work alongside other female artists who documented life behind the front lines.",
            hasImages: true,
            imageNote: "Rae's WWI pastel drawings, including 'German prisoners putting up tents'.",
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title: "Women Artists of WW1: Iso Rae — Josie Holford",
            url: "https://www.josieholford.com/women-artists-of-ww1-iso-rae/",
            summary:
              "An article on the exclusion of women from Australia's official war artist appointments in 1918, focusing on Rae's unrecognized contributions.",
            hasImages: true,
            imageNote: "Reproductions of her wartime pastel sketches.",
          },
        ],
      },
      {
        key: "news_press",
        label: "News & Press",
        entries: [
          {
            title: "Isobel (Iso) Rae — Gibson's Auctions",
            url: "https://www.gibsonsauctions.com.au/isobel-iso-rae/",
            summary:
              "A 2022 article on the rising market and institutional interest in Rae, noting the NGV's record-breaking acquisition of her work.",
            hasImages: true,
            imageNote: "Images of 'Breton Family' and 'Young Girl, Étaples'.",
          },
          {
            title:
              "Exciting art changeovers in the First World War, Second World War and Korea galleries — Australian War Memorial",
            url: "https://www.awm.gov.au/articles/blog/exciting-art-changeovers-in-the-galleries",
            summary:
              "A 2024 update from the Australian War Memorial on the installation of two of Rae's pastel drawings in their First World War Galleries.",
            hasImages: true,
            imageNote: "Images of the newly installed pastel drawings.",
          },
        ],
      },
    ],
  },
  {
    slug: "john-longstaff",
    name: "John Longstaff",
    dates: "1861–1941",
    connectionToPatterson:
      "Like Patterson, Longstaff trained at the National Gallery School in Melbourne before continuing his studies in Paris, part of the same generation of Australian artists who moved between Melbourne and Europe around the turn of the century. Longstaff went on to become Australia's first knighted artist and a five-time Archibald Prize winner, a very different path from Patterson's move into art education in Seattle.",
    overview:
      "Sir John Campbell Longstaff (1861–1941) was a distinguished Australian painter renowned for his portraiture and his role as an official war artist during World War I. He trained at the Melbourne National Gallery School before continuing in Paris, went on to win the Archibald Prize five times, and was knighted in 1928.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "John Longstaff — Wikipedia",
            url: "https://en.wikipedia.org/wiki/John_Longstaff",
            summary:
              "A comprehensive biographical overview covering Longstaff's education at the Melbourne National Gallery School, his career as a portraitist and war artist, his five Archibald Prize wins, and his knighthood.",
            hasImages: false,
          },
          {
            title: "LONGSTAFF, Sir John Campbell (1861–1941) — The Geelong College",
            url: "https://gnet.tgc.vic.edu.au/wiki/LONGSTAFF-Sir-John-Campbell-1861-1941",
            summary:
              "A biographical summary focusing on his time as an Official War Artist during World War I and his knighthood in 1928.",
            hasImages: false,
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "John Longstaff — Artists | NGV",
            url: "https://www.ngv.vic.gov.au/explore/collection/artist/1960/",
            summary:
              "The National Gallery of Victoria's collection page for Longstaff, listing 24 of his works held by the institution, including 'Gippsland, Sunday night, February 20th, 1898'.",
            hasImages: true,
            imageNote: "24 paintings and sketches in the NGV collection.",
          },
          {
            title: "John Longstaff — Australian War Memorial",
            url: "https://www.awm.gov.au/collection/C176452",
            summary:
              "The Australian War Memorial's collection page on Longstaff's work as an official war artist attached to the Australian Imperial Forces in 1918.",
            hasImages: true,
            imageNote: "Archival records and his commissioned military portraits from World War I.",
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "John Longstaff — 71 Artworks at Auction — MutualArt",
            url: "https://www.mutualart.com/Artist/John-Longstaff/50037EB6B43D814A",
            summary:
              "An auction database featuring over 70 artworks by Longstaff, including realized prices and exhibition history.",
            hasImages: true,
            imageNote: "Over 70 paintings and works on paper sold at auction.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "Lady in grey, John Longstaff — NGV",
            url: "https://www.ngv.vic.gov.au/explore/collection/work/5870/",
            summary:
              "An artwork detail page explaining the influence of James McNeill Whistler and European Japonisme on Longstaff's early Parisian work.",
            hasImages: true,
            imageNote: "The painting 'Lady in grey' and its original frame.",
          },
          {
            title: "William Frederick (Will) Longstaff — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/longstaff-william-frederick-will-7231",
            summary:
              "A biographical entry for Will Longstaff, John Longstaff's cousin and fellow official war artist.",
            hasImages: false,
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title:
              "Debonair Jack: A Biography of Sir John Longstaff, 1861–1941 — Prue Joske",
            url: "https://books.google.com.au/books/about/Debonair_Jack.html?id=jF141zOM8OIC&redir_esc=y",
            summary:
              "Prue Joske's 1994 comprehensive biography, covering his journey from a storekeeper's son to Australia's first knighted artist.",
            hasImages: false,
          },
        ],
      },
      {
        key: "news_press",
        label: "News & Press",
        entries: [
          {
            title: "Sir John Campbell Longstaff — Obituaries Australia",
            url: "https://oa.anu.edu.au/obituary/longstaff-sir-john-campbell-7230",
            summary:
              "A digitized 1941 obituary reflecting on Longstaff's death and legacy as the 'doyen of Australian artists'.",
            hasImages: false,
          },
          {
            title: "19 Jan 1929 — Archibald Prize won by John Longstaff — Trove",
            url: "https://trove.nla.gov.au/newspaper/article/54249995",
            summary:
              "A historical news clipping from Trove announcing Longstaff's 1928 Archibald Prize win.",
            hasImages: false,
          },
        ],
      },
    ],
  },
  {
    slug: "bernard-hall",
    name: "Bernard Hall",
    dates: "1859–1935",
    connectionToPatterson:
      "Hall was Patterson's teacher at the National Gallery School in Melbourne, and as the school's longest-serving director he shaped an entire generation of Australian artists who went on to Paris — including Hugh Ramsay, John Longstaff, Iso Rae, and E. Phillips Fox. His strict academic training was the common starting point for the whole expatriate circle Patterson belonged to.",
    overview:
      "Lindsay Bernard Hall (1859–1935) was an English-born Australian artist, teacher, and the longest-serving director of the National Gallery of Victoria. A strict disciplinarian who championed academic painting, his own work frequently featured nudes, interiors, and still lifes, though his administrative legacy — including acting as the first buyer for the Felton Bequest — has often overshadowed his artistic output.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "Lindsay Bernard Hall — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/hall-lindsay-bernard-6528",
            summary:
              "A comprehensive biographical entry detailing Hall's early life, education in London and Munich, and his 43-year tenure as director of the National Gallery of Victoria.",
            hasImages: false,
          },
          {
            title: "Lindsay Bernard Hall — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Lindsay_Bernard_Hall",
            summary:
              "An overview of Hall's life, career, and legacy as an artist and gallery director in Australia.",
            hasImages: true,
            imageNote: "A portrait of Hall and examples of his paintings.",
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "National Gallery of Victoria (NGV)",
            url: "https://www.ngv.vic.gov.au/",
            summary:
              "The NGV holds a significant collection of Hall's work, including his symbolist painting 'Sleep' (c. 1906); Hall served as its director from 1892 to 1935, shaping its collection through the Felton Bequest.",
            hasImages: false,
          },
          {
            title: "QAGOMA Collection Online",
            url: "https://collection.qagoma.qld.gov.au/",
            summary:
              "The Queensland Art Gallery holds notable works by Hall, including his unconventional 1922 Archibald Prize entry 'Lady with sponge'.",
            hasImages: false,
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "Lindsay Bernard Hall — Art Renewal Center",
            url: "https://www.artrenewal.org/artists/lindsay-bernard-hall/6468",
            summary:
              "A digital gallery of Hall's paintings, including 'Sleep', 'Processional', and 'Nude Reading at Studio Fire'.",
            hasImages: true,
            imageNote: "7 paintings showcasing his academic and symbolist styles.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "Louis Frederick McCubbin — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/mccubbin-louis-frederick-7329",
            summary:
              "Biography of Louis Frederick McCubbin, one of the many notable Australian artists who studied under Hall at the National Gallery School.",
            hasImages: false,
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title: "L. Bernard Hall: The Man the Art World Forgot",
            url: "https://www.tandfonline.com/doi/full/10.1080/14443058.2014.904727",
            summary:
              "An academic review in the Journal of Australian Studies discussing Gwen Rankin's definitive 2013 biography of Hall, exploring his dual role as artist and institutional director.",
            hasImages: false,
          },
        ],
      },
    ],
  },
];
