// Source data generated by scripts/search-engine (Gemini + Google Search
// research on each artist), reviewed by hand before landing here. See
// scripts/search-engine/output/<slug>.json for the raw research pass.

export interface Resource {
  title: string;
  url: string;
  summary: string;
  hasImages: boolean;
  imageNote?: string;
}

export interface ResourceCategory {
  key: string;
  label: string;
  entries: Resource[];
}

export interface RelatedArtist {
  slug: string;
  name: string;
  dates: string;
  /** Why this artist has a page on an Ambrose Patterson site — shown as an intro callout. */
  connectionToPatterson: string;
  overview: string;
  categories: ResourceCategory[];
  /** Optional link to a dedicated on-site video page about this artist. */
  video?: { href: string; label: string };
}

export const relatedArtists: RelatedArtist[] = [
  {
    slug: "hugh-ramsay",
    name: "Hugh Ramsay",
    dates: "1877–1906",
    connectionToPatterson:
      "Ramsay and Patterson trained together under Bernard Hall at the National Gallery School in Melbourne before both left for Paris around the turn of the century. In 1901–02 Ramsay painted a full-length portrait of Patterson; the canvas was later damaged, and Patterson himself cropped it down to the fragment held today by the National Portrait Gallery. Ramsay died of tuberculosis in 1906, aged 28, cutting short one of the most promising careers of his generation.",
    overview:
      "Hugh Ramsay (1877–1906) was a highly gifted Australian artist whose promising career was cut short by tuberculosis at age 28. He is celebrated for tonally subtle portraiture — influenced by Velázquez, Whistler, and Sargent — and achieved early success when four paintings were accepted into the 1902 New Salon in Paris. His work is held in major Australian institutions today.",
    video: {
      href: "/press/around-the-web/hugh-ramsay/video",
      label:
        "Watch: NGA curator Dr. Deborah Hart on Hugh Ramsay's short, brilliant life",
    },
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "Hugh Ramsay — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/ramsay-hugh-8150",
            summary:
              "A comprehensive biographical entry covering Ramsay's education at the National Gallery schools and his rapid rise to international acclaim before his early death.",
            hasImages: false,
          },
          {
            title: "Hugh Ramsay — National Portrait Gallery",
            url: "https://www.portrait.gov.au/people/hugh-ramsay-1877",
            summary:
              "An overview of Ramsay's life and career, his time in Paris, his critical success at the New Salon, and his patronage by Dame Nellie Melba.",
            hasImages: true,
            imageNote: "His 1901–1902 full-length self-portrait.",
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "Hugh Ramsay — Artists | NGV",
            url: "https://www.ngv.vic.gov.au/explore/collection/artist/488/",
            summary:
              "The National Gallery of Victoria's collection page for Ramsay, listing 21 of his works held by the institution.",
            hasImages: true,
            imageNote:
              "21 artworks in the NGV collection, including self-portraits and studies.",
          },
          {
            title:
              "Hugh Ramsay Exhibition Tour — National Gallery of Australia",
            url: "https://nga.gov.au/on-demand/hugh-ramsay-exhibition-tour/",
            summary:
              "The NGA's major retrospective of Ramsay, the first in over 25 years, curating paintings, drawings, sketchbooks, and letters from collections nationwide.",
            hasImages: false,
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "Hugh Ramsay Works — National Gallery of Australia",
            url: "https://nga.gov.au/ramsay/works.cfm",
            summary:
              "A gallery page showcasing the artworks displayed in the NGA's comprehensive Hugh Ramsay retrospective.",
            hasImages: true,
            imageNote:
              "High-resolution images of works from the NGA retrospective.",
          },
          {
            title:
              "The art and archive of Hugh Ramsay — National Gallery of Australia",
            url: "https://nga.gov.au/stories-ideas/the-art-and-archive-of-hugh-ramsay/",
            summary:
              "An archival look at Ramsay's painting tools, photographs, letters, and sketchbooks.",
            hasImages: true,
            imageNote:
              "His wooden paintbox, watercolour tins, brushes, and a self-portrait smoking in front of a piano.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "Portrait of Ambrose Patterson — National Portrait Gallery",
            url: "https://www.portrait.gov.au/portraits/2003.44/portrait-of-ambrose-patterson",
            summary:
              "Ramsay's 1901–1902 portrait of his friend and fellow Australian expatriate Ambrose Patterson, painted in Paris — later damaged and cropped by Patterson himself.",
            hasImages: true,
            imageNote: "Image of the cropped portrait of Ambrose Patterson.",
          },
          {
            title: "Hugh Ramsay Symposium — Ramsay + Lambert",
            url: "https://nga.gov.au/on-demand/hugh-ramsay-symposium-gray-nga-ramsay-lambert/",
            summary:
              "A lecture on the close relationship and mutual influence between Ramsay and fellow Australian artist George Lambert during their time in Paris, studying Velázquez and Sargent together.",
            hasImages: false,
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title: "Hugh Ramsay: His Life and Work — Patricia Fullerton",
            url: "https://www.treloars.com/pages/books/143053/hugh-ramsay-patricia-fullerton/hugh-ramsay-his-life-and-work",
            summary:
              "The definitive 1988 monograph, based largely on Ramsay's own letters — a crucial text for researchers.",
            hasImages: false,
          },
          {
            title:
              "Hugh Ramsay: a consideration of his life and work — Minerva Access",
            url: "https://minerva-access.unimelb.edu.au/handle/11343/37215",
            summary:
              "A University of Melbourne thesis offering a scholarly consideration of Ramsay's life, family background, and artistic output.",
            hasImages: false,
          },
        ],
      },
      {
        key: "news_press",
        label: "News & Press",
        entries: [
          {
            title:
              "Hugh Ramsay review: a virtuoso of white on white who left the art world too soon",
            url: "https://theconversation.com/hugh-ramsay-review-a-virtuoso-of-white-on-white-who-left-the-art-world-too-soon-126587",
            summary:
              "A 2019 review of the NGA's retrospective, praising Ramsay's virtuosic technique and lamenting the early loss of his talent.",
            hasImages: false,
          },
          {
            title: "Hugh Ramsay: Bright Star — National Gallery of Australia",
            url: "https://nga.gov.au/stories-ideas/hugh-ramsay-bright-star/",
            summary:
              "A feature by the NGA's Head Curator of Australian Art drawing parallels between Ramsay and the poet John Keats, both dead of tuberculosis at a young age.",
            hasImages: true,
            imageNote:
              "Ramsay's self-portraits and key paintings discussed in the article.",
          },
        ],
      },
    ],
  },
  {
    slug: "george-w-lambert",
    name: "George W. Lambert",
    dates: "1873–1930",
    connectionToPatterson:
      "Lambert painted a group self-portrait, held by the National Gallery of Australia, that included Patterson alongside Hugh Ramsay, Amy Lambert, and the writer Arthur Adams — a document of the same Paris bohemian circle Patterson moved in as a young expatriate. Like Patterson, Lambert trained in Melbourne before continuing his studies abroad, and the two crossed paths through the same close-knit group of Australian artists in Paris around the turn of the century.",
    overview:
      "George Washington Lambert (1873–1930) was a prominent Australian artist known for his portraiture, 'puzzle pictures', and his work as an official war artist during World War I. He trained in Melbourne before moving through Paris and London, and became one of the most influential Australian artists of his generation.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "George Washington Lambert — Wikipedia",
            url: "https://en.wikipedia.org/wiki/George_Washington_Lambert",
            summary:
              "A comprehensive biographical overview covering Lambert's early years, his career as an official war artist, and his later sculptural work, with details on his influences and major exhibitions.",
            hasImages: true,
            imageNote: "Paintings and a photograph of the artist.",
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "Important People (Lambert) — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Important_People_(Lambert)",
            summary:
              "Details Lambert's 1914–1921 painting 'Important People', held at the Art Gallery of New South Wales, its allegorical meaning and critical reception.",
            hasImages: true,
            imageNote: "High-resolution image of 'Important People'.",
          },
          {
            title: "A Sergeant of the Light Horse — Wikipedia",
            url: "https://en.wikipedia.org/wiki/A_Sergeant_of_the_Light_Horse",
            summary:
              "Lambert's 1920 portrait of an Australian soldier in Palestine, held by the NGV, and his approach to composite military portraiture.",
            hasImages: true,
            imageNote: "High-resolution image of the painting.",
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title:
              "Category: Paintings by George Washington Lambert — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Category:Paintings_by_George_Washington_Lambert",
            summary:
              "A hub listing articles on individual paintings by Lambert, with images and analysis across various periods of his career.",
            hasImages: false,
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title:
              "Self-portrait with Ambrose Patterson, Amy Lambert, Hugh Ramsay and Arthur Adams — National Gallery of Australia",
            url: "https://digital.nga.gov.au/archive/exhibition/lambert/detail.cfm%3Firn=163176.html",
            summary:
              "A group portrait by Lambert featuring Ambrose Patterson alongside other expatriate Australian artists in Paris, with context on their shared bohemian circle.",
            hasImages: true,
            imageNote: "Image of the group portrait featuring Patterson.",
          },
          {
            title: "The White Glove — Wikipedia",
            url: "https://en.wikipedia.org/wiki/The_White_Glove",
            summary:
              "Lambert's 1921 portrait of Miss Gladys Neville Collins, highlighting the influence of Joshua Reynolds and John Singer Sargent on his style.",
            hasImages: true,
            imageNote: "Image of the painting.",
          },
          {
            title: "Self-Portrait with Gladioli — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Self-Portrait_with_Gladioli",
            summary:
              "Analysis of Lambert's 1922 self-portrait and its resemblance to Reynolds' self-portraits and classical sculpture.",
            hasImages: true,
            imageNote: "Image of the painting.",
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title: "Chesham Street — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Chesham_Street",
            summary:
              "Lambert's 1910 'puzzle picture' depicting a medical examination, with context on his Edwardian period and use of narrative ambiguity.",
            hasImages: true,
            imageNote: "Image of the painting.",
          },
          {
            title: "Anzacs Bathing — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Anzacs_Bathing",
            summary:
              "Lambert's 1916 painting of soldiers at Gallipoli, and his references to Michelangelo and Greek mythology as an official war artist.",
            hasImages: true,
            imageNote: "Image of the painting.",
          },
        ],
      },
    ],
  },
  {
    slug: "rupert-bunny",
    name: "Rupert Bunny",
    dates: "1864–1947",
    connectionToPatterson:
      "Bunny was part of the wider generation of Australian expatriate painters — Patterson among them — who left Melbourne for Paris around the turn of the century and built careers exhibiting in the French Salon system. The two moved in overlapping circles of Australian artists living and showing work in Paris during the Belle Époque, before Patterson's own path continued on to Hawaii and Seattle.",
    overview:
      "Rupert Bunny (1864–1947) was one of the most successful Australian expatriate artists of his generation, spending nearly 50 years in France. He is celebrated for sumptuous Belle Époque paintings of Parisian leisure, mythological scenes, and later landscapes, achieving significant recognition in the French Salon system.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "Rupert Charles Bunny — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/bunny-rupert-charles-5422/text9195",
            summary:
              "A comprehensive biographical entry on Bunny's early life in Melbourne, his career in Paris, and his return to Australia.",
            hasImages: false,
          },
          {
            title: "Rupert Bunny — Wikipedia",
            url: "https://en.wikipedia.org/wiki/Rupert_Bunny",
            summary:
              "An overview of Bunny's life, education, and success at the Paris Salon, covering his transition from neoclassical and symbolist work to later landscapes.",
            hasImages: true,
            imageNote:
              "A self-portrait and several of his most famous paintings.",
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "Rupert BUNNY — Collection Online | NGV",
            url: "https://www.ngv.vic.gov.au/explore/collection/artist/1149/",
            summary:
              "The NGV's substantial Bunny collection, including his 'Madame Melba' portrait and numerous sketches.",
            hasImages: true,
            imageNote:
              "Over 80 artworks including major paintings and preparatory sketches.",
          },
          {
            title: "Rupert Bunny — National Gallery of Australia",
            url: "https://nga.gov.au/exhibitions/rupert-bunny/",
            summary:
              "The NGA's collection of more than 100 works by Bunny, from early botanical garden landscapes to late mythological paintings.",
            hasImages: true,
            imageNote: "Images of key works like 'Qui vient? [Who comes?]'.",
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "Rupert Bunny — 59 artworks — WikiArt.org",
            url: "https://www.wikiart.org/en/rupert-bunny",
            summary:
              "A visual database of Bunny's paintings organized chronologically and by style, spanning his Belle Époque and mythological works.",
            hasImages: true,
            imageNote: "Dozens of images filterable by date and genre.",
          },
          {
            title: "Rupert Bunny Artworks at Auction — MutualArt",
            url: "https://www.mutualart.com/Artist/Rupert-Bunny",
            summary:
              "An archive of over 400 artworks by Bunny that have appeared at auction, spanning landscapes, portraits, and sketches in private collections.",
            hasImages: true,
            imageNote: "Hundreds of images from auction records.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "Rupert Bunny's Mythologies — National Gallery of Australia",
            url: "https://nga.gov.au/exhibitions/rupert-bunnys-mythologies/",
            summary:
              "An essay on Bunny's fascination with classical and Christian mythology, and how he assimilated Symbolism and Puvis de Chavannes into his own allegorical style.",
            hasImages: false,
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title:
              "The life and art of Rupert Bunny: a catalogue raisonné in two volumes",
            url: "https://catalogue.nla.gov.au/catalog/7289251",
            summary:
              "David Thomas's definitive 2017 two-volume catalogue raisonné, covering Bunny's oils, monotypes, sketchbooks, and exhibition history.",
            hasImages: false,
          },
          {
            title: "Rupert Bunny, 1864–1947 — David Thomas",
            url: "https://catalogue.nla.gov.au/catalog/642369",
            summary:
              "The original 1970 monograph on Bunny, a foundational text for studying his life and early critical reception.",
            hasImages: false,
          },
        ],
      },
      {
        key: "news_press",
        label: "News & Press",
        entries: [
          {
            title:
              "The Cosmopolitans: In Gallery Two — National Portrait Gallery",
            url: "https://www.portrait.gov.au/exhibitions/the-cosmopolitans-2023",
            summary:
              "A 2023–2024 exhibition featuring Bunny alongside his contemporaries, highlighting the generation of Australian artists who traveled to London and Paris around 1900.",
            hasImages: true,
            imageNote:
              "Installation views and selected portraits from the exhibition.",
          },
          {
            title:
              "Rupert Bunny Foundation Visual Arts Fellowship — City of Port Phillip",
            url: "https://www.portphillip.vic.gov.au/people-and-community/funds-grants-and-subsidies/rupert-bunny-foundation-visual-arts-fellowship",
            summary:
              "A contemporary visual arts fellowship established in 2005 using funds from the insurance of a destroyed Rupert Bunny painting.",
            hasImages: false,
          },
        ],
      },
    ],
  },
  {
    slug: "e-phillips-fox",
    name: "E. Phillips Fox",
    dates: "1865–1915",
    connectionToPatterson:
      "Like Patterson, Fox trained in Melbourne before continuing his studies in Paris, and both were part of the wave of Australian expatriate painters who carried French Impressionist and Post-Impressionist technique back into Australian art. Fox's role co-founding the Melbourne School of Art parallels Patterson's own later move into art education, when he went on to establish the University of Washington's School of Painting and Design.",
    overview:
      "Emanuel Phillips Fox (1865–1915) was a prominent Australian Impressionist and Post-Impressionist painter celebrated for his vibrant use of light and color. After training in Melbourne and Paris, he became a key figure in the Heidelberg School and co-founded the Melbourne School of Art, often in creative partnership with his wife, the artist Ethel Carrick Fox.",
    categories: [
      {
        key: "biography_background",
        label: "Biography & Background",
        entries: [
          {
            title: "Emanuel Phillips Fox — Australian Dictionary of Biography",
            url: "https://adb.anu.edu.au/biography/fox-emanuel-phillips-6228",
            summary:
              "An authoritative academic biography detailing Fox's training under Gérôme in Paris and his establishment of the Melbourne School of Art.",
            hasImages: false,
          },
          {
            title: "E. Phillips Fox — Wikipedia",
            url: "https://en.wikipedia.org/wiki/E._Phillips_Fox",
            summary:
              "A comprehensive overview of Fox's early life in Melbourne, his studies in Europe, his role in the second phase of the Heidelberg School, and his marriage to Ethel Carrick.",
            hasImages: false,
          },
        ],
      },
      {
        key: "galleries_museums",
        label: "Galleries & Museums",
        entries: [
          {
            title: "E. Phillips Fox — National Portrait Gallery",
            url: "https://www.portrait.gov.au/people/emanuel-phillips-fox-1865",
            summary:
              "The National Portrait Gallery's collection page for Fox, with a biographical summary of his time in France and England and his portraiture work.",
            hasImages: true,
            imageNote:
              "Portraits by Fox held in the National Portrait Gallery collection.",
          },
          {
            title:
              "Between the Bush and Boudoir — National Gallery of Australia",
            url: "https://nga.gov.au/exhibitions/between-the-bush-and-boudoir/",
            summary:
              "An overview of Fox's place among a new generation of Australian impressionists in the 1880s, blending European plein-air traditions with Australian subjects.",
            hasImages: false,
          },
        ],
      },
      {
        key: "image_sources",
        label: "Image Sources",
        entries: [
          {
            title: "Emanuel Phillips Fox — 82 artworks — Art Renewal Center",
            url: "https://www.artrenewal.org/artists/emanuel-phillips-fox/2181",
            summary:
              "A digital gallery of Fox's paintings, drawings, and oils, showcasing his mastery of light and color.",
            hasImages: true,
            imageNote:
              "High-resolution images of 82 artworks spanning his career.",
          },
          {
            title:
              "Emanuel Phillips Fox: A collection of 76 paintings (HD) — YouTube",
            url: "https://www.youtube.com/watch?v=TKlUlRkb6Us",
            summary:
              "A video compilation of 76 of Fox's paintings in high definition, with a biographical description covering his landscapes, portraits, and Edwardian scenes.",
            hasImages: true,
            imageNote: "Video slideshow of 76 high-definition images.",
          },
        ],
      },
      {
        key: "influences_related",
        label: "Influences & Related",
        entries: [
          {
            title: "The poetry of the world — National Gallery of Australia",
            url: "https://nga.gov.au/stories-ideas/the-poetry-of-the-world/",
            summary:
              "An essay on Ethel Carrick, Fox's wife and a significant Post-Impressionist painter in her own right, contextualizing their mutual support and shared travels.",
            hasImages: true,
            imageNote: "Ethel Carrick's paintings and archival material.",
          },
          {
            title:
              "Ethel Carrick Fox and Emanuel Phillips Fox: A Historic Partnership — Leonard Joel Auctions",
            url: "https://www.leonardjoel.com.au/newsletter/the-estate-of-graham-joel/",
            summary:
              "An article on the artistic partnership between Fox and Ethel Carrick Fox, and their shared life of en plein air painting across Europe and North Africa after their 1905 marriage.",
            hasImages: false,
          },
        ],
      },
      {
        key: "further_reading",
        label: "Further Reading",
        entries: [
          {
            title: "E. Phillips Fox: His Life and Art — Ruth Zubans",
            url: "https://books.google.com.au/books/about/E_Phillips_Fox.html?id=VbILAQAAMAAJ&redir_esc=y",
            summary:
              "A comprehensive 1995 monograph by art historian Ruth Zubans, considered the definitive text on Fox's life, Paris years, and development of Impressionist subject painting.",
            hasImages: false,
          },
        ],
      },
      {
        key: "news_press",
        label: "News & Press",
        entries: [
          {
            title: "Ethel Carrick — National Gallery of Australia",
            url: "https://nga.gov.au/exhibitions/ethel-carrick/",
            summary:
              "A major retrospective of Ethel Carrick (Dec 2024 – Apr 2025) re-evaluating her career and output during and after her marriage to Fox.",
            hasImages: true,
            imageNote:
              "Promotional images and selected artworks from the exhibition.",
          },
          {
            title: "CAM celebrates painting prize — Midland Express",
            url: "https://midlandexpress.com.au/latest-news/2024/10/01/len-fox-painting-award-celebrated-at-castlemaine-art-museum/",
            summary:
              "Coverage of the 2024 Len Fox Painting Award at the Castlemaine Art Museum, a biennial prize commemorating Fox's life and work.",
            hasImages: false,
          },
        ],
      },
    ],
  },
];
